{
  "hash": "b6ae95b6e1e3e07624636ae5a289a928",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"gapminder 탐색적 분석(EDA) 보고서\"\nauthor: \"yewonyu\"\ndate: \"2026-06-27\"\nlang: ko\nformat:\n  html:\n    theme: cosmo\n    toc: true\n    toc-depth: 3\n    toc-title: \"목차\"\n    number-sections: true\n    code-fold: true\n    code-tools: true\n    code-summary: \"코드 보기\"\n    fig-width: 8\n    fig-height: 5\n    fig-dpi: 120\n    df-print: kable\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n  echo: true\nknitr:\n  opts_chunk:\n    comment: \"#>\"\n---\n\n\n\n\n> **분석 대상**: gapminder_clean.csv (1,704행, 142개국 × 12개 연도) ·\n> **스크립트**: `eda.R` / 본 문서 `eda_report.qmd` ·\n> **그림**: 본 문서 내 인라인 생성\n>\n> 본 보고서의 **모든 수치·표·그림은 원자료에서 직접 계산**된다(Quarto 재현 가능 문서). 왜도·첨도·지니·잔차는 외부 패키지 없이 구현했다.\n\n---\n\n# 데이터 무결성 점검\n\n분포·관계 분석에 앞서 데이터 품질을 먼저 확인한다. 결론의 신뢰도는 입력 품질을 넘을 수 없다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexpected_cols <- c(\"country\",\"year\",\"pop\",\"continent\",\"lifeExp\",\"gdpPercap\")\nyears_all   <- sort(unique(df$year))\nper_country <- df %>% count(country, name = \"n_years\")\nbalanced    <- all(per_country$n_years == length(years_all))\nexpected_conts <- c(\"Africa\",\"Americas\",\"Asia\",\"Europe\",\"Oceania\")\nbad_conts <- setdiff(levels(df$continent), expected_conts)\n\nintegrity <- data.frame(\n  점검항목 = c(\"필수 컬럼\", \"행 수 / 컬럼\", \"결측치(NA)\",\n               \"(국가,연도) 키 중복\", \"값 범위 위반\",\n               \"대륙 라벨\", \"연도 집합\", \"국가 수\", \"패널 균형성\"),\n  결과 = c(\n    if (length(setdiff(expected_cols, names(df)))==0) \"모두 존재\" else \"누락 있음\",\n    sprintf(\"%s행 / %d열\", format(nrow(df), big.mark=\",\"), ncol(df)),\n    sprintf(\"%d건\", sum(is.na(df))),\n    sprintf(\"%d건\", sum(duplicated(df[, c(\"country\",\"year\")]))),\n    sprintf(\"lifeExp %d · gdp %d · pop %d 건\",\n            sum(df$lifeExp<=0 | df$lifeExp>120, na.rm=TRUE),\n            sum(df$gdpPercap<=0, na.rm=TRUE),\n            sum(df$pop<=0, na.rm=TRUE)),\n    if (length(bad_conts)==0) paste(levels(df$continent), collapse=\", \") else paste(\"이상:\", paste(bad_conts, collapse=\", \")),\n    sprintf(\"%d–%d, %d개\", min(years_all), max(years_all), length(years_all)),\n    sprintf(\"%d개국\", n_distinct(df$country)),\n    if (balanced) \"균형 패널 (모든 국가가 동일 연도 보유)\" else \"불균형\"\n  )\n)\nkable(integrity, caption = \"데이터 무결성 점검 결과\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 데이터 무결성 점검 결과\n\n|점검항목            |결과                                    |\n|:-------------------|:---------------------------------------|\n|필수 컬럼           |모두 존재                               |\n|행 수 / 컬럼        |1,704행 / 6열                           |\n|결측치(NA)          |0건                                     |\n|(국가,연도) 키 중복 |0건                                     |\n|값 범위 위반        |lifeExp 0 · gdp 0 · pop 0 건          |\n|대륙 라벨           |Africa, Americas, Asia, Europe, Oceania |\n|연도 집합           |1952–2007, 12개                         |\n|국가 수             |142개국                                 |\n|패널 균형성         |균형 패널 (모든 국가가 동일 연도 보유)  |\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n## 데이터 함정: 따옴표 없는 CSV의 열 밀림\n원본 `data/gapminder.csv`는 따옴표가 없어 `Korea, Rep.`·`Congo, Dem. Rep.`·`Yemen, Rep.`처럼 **쉼표가 포함된 국가명이 열을 밀어** 대륙 라벨이 깨질 수 있다. 따옴표 처리된 `gapminder_clean.csv`를 사용하면 대륙 라벨이 정확히 5종으로 떨어진다(위 점검에서 확인). 본 문서는 매 렌더 시 라벨 타당성을 자동 검사한다.\n:::\n\n# 주요 변수 분포\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnum_vars <- c(\"lifeExp\",\"gdpPercap\",\"pop\")\ndist_tbl <- do.call(rbind, lapply(num_vars, function(v) {\n  x <- df[[v]]; q <- quantile(x, c(0,.25,.5,.75,1), na.rm = TRUE)\n  data.frame(변수=v, 평균=mean(x), 표준편차=sd(x),\n             최소=q[[1]], Q1=q[[2]], 중앙값=q[[3]], Q3=q[[4]], 최대=q[[5]],\n             왜도=skewness(x), 초과첨도=kurtosis_excess(x))\n}))\nkable(dist_tbl, digits = 2, format.args = list(big.mark=\",\"),\n      caption = \"주요 변수 요약 통계 (전체 1,704 관측)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 주요 변수 요약 통계 (전체 1,704 관측)\n\n|변수      |          평균|       표준편차|      최소|           Q1|       중앙값|            Q3|            최대|  왜도| 초과첨도|\n|:---------|-------------:|--------------:|---------:|------------:|------------:|-------------:|---------------:|-----:|--------:|\n|lifeExp   |         59.47|          12.92|     23.60|        48.20|        60.71|         70.85|            82.6| -0.25|    -1.13|\n|gdpPercap |      7,215.33|       9,857.45|    241.17|     1,202.06|     3,531.85|      9,325.46|       113,523.1|  3.85|    27.40|\n|pop       | 29,601,212.33| 106,157,896.75| 60,011.00| 2,793,664.00| 7,023,595.50| 19,585,221.75| 1,318,683,096.0|  8.34|    77.62|\n\n\n:::\n:::\n\n\n- **gdpPercap·pop**: 왜도가 크게 양(+)이고 평균이 중앙값을 크게 상회 → 강한 **우편향**. 분석·시각화 시 **로그 변환** 필수.\n- **lifeExp**: 흔히 \"대칭\"으로 단순화되지만 실제로는 **약한 좌편향(왜도 ≈ −0.25)**, **초과첨도 ≈ −1.1(평평/이봉 경향)**. 이는 1952년과 2007년을 **한데 모은** 탓이며, 통합 히스토그램의 두 봉우리(과거 저수명군 vs 현재 고수명군)는 연도를 분리하면 사라진다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(lifeExp)) +\n  geom_histogram(bins = 30, fill = \"#2c7fb8\", color = \"white\") +\n  labs(x = \"기대수명\", y = \"빈도\") + theme_minimal()\n```\n\n::: {.cell-output-display}\n![기대수명 분포 — 전체 연도 통합(시대 혼합으로 이봉 경향)](eda_report_files/figure-html/fig-hist-life-1.png){#fig-hist-life width=960}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(gdpPercap)) +\n  geom_histogram(bins = 30, fill = \"#31a354\", color = \"white\") +\n  scale_x_log10(labels = scales::comma) +\n  labs(x = \"gdpPercap (log10)\", y = \"빈도\") + theme_minimal()\n```\n\n::: {.cell-output-display}\n![1인당 GDP 분포 (로그 스케일)](eda_report_files/figure-html/fig-hist-gdp-1.png){#fig-hist-gdp width=960}\n:::\n:::\n\n\n# 시간에 따른 추세 — 중심 + 격차\n\n가중평균만 보면 \"중심\"은 보이지만 \"격차\"는 보이지 않는다. 인구 가중/비가중 평균과 함께 국가 간 **표준편차·지니계수**를 본다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrend <- df %>%\n  group_by(year) %>%\n  summarise(\n    가중평균수명 = weighted.mean(lifeExp, pop),\n    비가중평균수명 = mean(lifeExp),\n    가중1인당GDP = weighted.mean(gdpPercap, pop),\n    총인구_억 = sum(pop)/1e8,\n    수명SD = sd(lifeExp),\n    수명지니 = gini(lifeExp),\n    GDP지니 = gini(gdpPercap),\n    .groups = \"drop\"\n  )\nkable(trend, digits = 2, format.args = list(big.mark=\",\"),\n      caption = \"연도별 추세: 중심(가중평균)과 격차(SD·지니)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 연도별 추세: 중심(가중평균)과 격차(SD·지니)\n\n|  year| 가중평균수명| 비가중평균수명| 가중1인당GDP| 총인구_억| 수명SD| 수명지니| GDP지니|\n|-----:|------------:|--------------:|------------:|---------:|------:|--------:|-------:|\n| 1,952|        48.94|          49.06|     2,923.89|     24.07|  12.23|     0.14|    0.59|\n| 1,957|        52.12|          51.51|     3,338.93|     26.64|  12.23|     0.14|    0.58|\n| 1,962|        52.32|          53.61|     3,794.89|     29.00|  12.10|     0.13|    0.57|\n| 1,967|        56.98|          55.68|     4,428.34|     32.17|  11.72|     0.12|    0.56|\n| 1,972|        59.51|          57.65|     5,150.00|     35.77|  11.38|     0.11|    0.57|\n| 1,977|        61.24|          59.57|     5,678.86|     39.30|  11.23|     0.11|    0.55|\n| 1,982|        62.88|          61.53|     5,917.32|     42.89|  10.77|     0.10|    0.54|\n| 1,987|        64.42|          63.21|     6,422.88|     46.91|  10.56|     0.09|    0.55|\n| 1,992|        65.65|          64.16|     6,750.71|     51.11|  11.23|     0.10|    0.56|\n| 1,997|        66.85|          65.01|     7,435.10|     55.15|  11.56|     0.10|    0.57|\n| 2,002|        67.84|          65.69|     8,028.96|     58.87|  12.28|     0.10|    0.57|\n| 2,007|        68.92|          67.01|     9,295.99|     62.51|  12.07|     0.10|    0.57|\n\n\n:::\n:::\n\n- 55년간 가중평균 기대수명 **+48.9년**(48.9 → 68.9세), 가중 1인당 GDP **약 3.2배**.\n- **격차는 U자형**: 국가 간 수명 SD가 12.2(1952) → 최저 **10.6(1987)** → 12.1(2007)로, 1980년대까지 수렴한 뒤 HIV/AIDS·체제전환으로 **재발산**. \"꾸준한 수렴\" 서사는 틀렸다.\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(factor(year), lifeExp)) +\n  geom_boxplot(fill = \"#a6bddb\", outlier.size = 0.6) +\n  labs(x = \"연도\", y = \"기대수명\") + theme_minimal()\n```\n\n::: {.cell-output-display}\n![연도별 기대수명 분포 변화](eda_report_files/figure-html/fig-box-year-1.png){#fig-box-year width=960}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(trend, aes(year, 수명SD)) +\n  geom_line(color = \"#d95f0e\", linewidth = 1) + geom_point(color = \"#d95f0e\") +\n  labs(x = \"연도\", y = \"기대수명 표준편차\") + theme_minimal()\n```\n\n::: {.cell-output-display}\n![국가 간 기대수명 격차(표준편차)의 시간 변화 — 하락=수렴, 상승=발산](eda_report_files/figure-html/fig-dispersion-1.png){#fig-dispersion width=960}\n:::\n:::\n\n\n# 대륙별 비교 (2007년)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nby_cont <- latest %>%\n  group_by(continent) %>%\n  summarise(국가수=n(), 수명중앙값=median(lifeExp), 수명IQR=IQR(lifeExp),\n            GDP중앙값=median(gdpPercap), 총인구_억=sum(pop)/1e8, .groups=\"drop\") %>%\n  arrange(desc(수명중앙값))\nkable(by_cont, digits = 2, format.args = list(big.mark=\",\"),\n      caption = sprintf(\"대륙별 요약 (%d년)\", latest_year))\n```\n\n::: {.cell-output-display}\n\n\nTable: 대륙별 요약 (2007년)\n\n|continent | 국가수| 수명중앙값| 수명IQR| GDP중앙값| 총인구_억|\n|:---------|------:|----------:|-------:|---------:|---------:|\n|Oceania   |      2|      80.72|    0.52| 29,810.19|      0.25|\n|Europe    |     30|      78.61|    4.78| 28,054.07|      5.86|\n|Americas  |     25|      72.90|    4.63|  8,948.10|      8.99|\n|Asia      |     33|      72.40|   10.15|  4,471.06|     38.12|\n|Africa    |     52|      52.93|   11.61|  1,452.27|      9.30|\n\n\n:::\n:::\n\n\n- 아프리카가 기대수명·소득 모두에서 큰 격차로 최하위.\n- **중앙값만으로는 부족하다**: IQR을 보면 **아프리카·아시아는 대륙 내부 이질성이 매우 크다**(약 10–12 vs 유럽·아메리카 약 5). 두 대륙은 하나로 묶어 말하기 어렵다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(latest, aes(reorder(continent, lifeExp, median), lifeExp, fill = continent)) +\n  geom_boxplot(show.legend = FALSE) +\n  geom_jitter(width = 0.15, size = 0.6, alpha = 0.4) +\n  coord_flip() + labs(x = \"대륙\", y = \"기대수명\") + theme_minimal()\n```\n\n::: {.cell-output-display}\n![대륙별 기대수명 분포 (개별 국가 점 포함)](eda_report_files/figure-html/fig-box-cont-1.png){#fig-box-cont width=960}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>% group_by(continent, year) %>%\n  summarise(lifeExp = weighted.mean(lifeExp, pop), .groups=\"drop\") %>%\n  ggplot(aes(year, lifeExp, color = continent)) +\n  geom_line(linewidth = 1) + geom_point(size = 1.5) +\n  labs(x = \"연도\", y = \"기대수명\", color = \"대륙\") + theme_minimal()\n```\n\n::: {.cell-output-display}\n![대륙별 기대수명 추세 (인구 가중)](eda_report_files/figure-html/fig-line-cont-1.png){#fig-line-cont width=960}\n:::\n:::\n\n\n# 1인당 GDP와 기대수명의 관계\n\n통합(pooled) 상관은 \"국가 간 차이\"와 \"시간에 따른 동반 상승\"을 **뒤섞는다**. 단일 연도 단면 상관과 비교해 효과를 분리한다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorr_tbl <- data.frame(\n  측정방식 = c(\"통합 · 원자료\", \"통합 · log10(GDP)\",\n               sprintf(\"%d년 단면 · log10(GDP)\", latest_year)),\n  상관계수 = c(cor(df$gdpPercap, df$lifeExp),\n               cor(log10(df$gdpPercap), df$lifeExp),\n               cor(log10(latest$gdpPercap), latest$lifeExp))\n)\nkable(corr_tbl, digits = 3, caption = \"GDP–기대수명 상관\")\n```\n\n::: {.cell-output-display}\n\n\nTable: GDP–기대수명 상관\n\n|측정방식                  | 상관계수|\n|:-------------------------|--------:|\n|통합 · 원자료            |    0.584|\n|통합 · log10(GDP)        |    0.808|\n|2007년 단면 · log10(GDP) |    0.809|\n\n\n:::\n\n```{.r .cell-code}\ncorr_by_year <- df %>% group_by(year) %>%\n  summarise(`log GDP 단면 상관` = cor(log10(gdpPercap), lifeExp), .groups=\"drop\")\nkable(corr_by_year, digits = 3, caption = \"연도별 단면 상관(log10 GDP) — 관계 강도의 시대 변화\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 연도별 단면 상관(log10 GDP) — 관계 강도의 시대 변화\n\n| year| log GDP 단면 상관|\n|----:|-----------------:|\n| 1952|             0.748|\n| 1957|             0.759|\n| 1962|             0.771|\n| 1967|             0.773|\n| 1972|             0.789|\n| 1977|             0.814|\n| 1982|             0.846|\n| 1987|             0.874|\n| 1992|             0.856|\n| 1997|             0.864|\n| 2002|             0.825|\n| 2007|             0.809|\n\n\n:::\n:::\n\n\n- 로그 변환 시 선형성이 뚜렷해진다(0.58 → 0.81). 단, **연도별 단면 상관은 0.75–0.87 사이를 오간다** — 관계의 강도 자체가 시대에 따라 달라지므로 \"하나의 상수\"로 말하면 안 된다.\n- 고소득 구간에서 기대수명 증가가 둔화되는 **포화(수확 체감)** 가 로그 스케일에서도 보인다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(lifeExp ~ log10(gdpPercap), data = latest)\nlatest$resid <- resid(fit)\nneg <- latest %>% arrange(resid) %>%\n  transmute(국가=country, 대륙=continent, 기대수명=round(lifeExp,1),\n            `1인당GDP`=round(gdpPercap), 잔차=round(resid,1)) %>% head(5)\npos <- latest %>% arrange(desc(resid)) %>%\n  transmute(국가=country, 대륙=continent, 기대수명=round(lifeExp,1),\n            `1인당GDP`=round(gdpPercap), 잔차=round(resid,1)) %>% head(5)\n```\n:::\n\n\n2007년 로그-선형 회귀 `lifeExp ~ log10(gdpPercap)`: **R² = 0.654**, 기울기 ≈ 16.6(GDP 10배당 +16.6년). 회귀선에서 벗어난 국가는 \"돈으로 설명 안 되는\" 사례다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(neg, format.args = list(big.mark=\",\"),\n      caption = \"소득 대비 수명이 낮은 국가(음의 잔차) — 2007년엔 HIV/AIDS 남부 아프리카가 지배적\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 소득 대비 수명이 낮은 국가(음의 잔차) — 2007년엔 HIV/AIDS 남부 아프리카가 지배적\n\n|국가              |대륙   | 기대수명| 1인당GDP|  잔차|\n|:-----------------|:------|--------:|--------:|-----:|\n|Swaziland         |Africa |     39.6|    4,513| -25.9|\n|Angola            |Africa |     42.7|    4,797| -23.3|\n|Botswana          |Africa |     50.7|   12,570| -22.2|\n|South Africa      |Africa |     49.3|    9,270| -21.4|\n|Equatorial Guinea |Africa |     51.6|   12,154| -21.1|\n\n\n:::\n\n```{.r .cell-code}\nkable(pos, format.args = list(big.mark=\",\"),\n      caption = \"소득 대비 수명이 높은 국가(양의 잔차) — 저소득 고성과\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 소득 대비 수명이 높은 국가(양의 잔차) — 저소득 고성과\n\n|국가               |대륙     | 기대수명| 1인당GDP| 잔차|\n|:------------------|:--------|--------:|--------:|----:|\n|Vietnam            |Asia     |     74.2|    2,442| 13.1|\n|Nicaragua          |Americas |     72.9|    2,749| 10.9|\n|West Bank and Gaza |Asia     |     73.4|    3,025| 10.7|\n|Comoros            |Africa   |     65.2|      986| 10.5|\n|Korea, Dem. Rep.   |Asia     |     67.3|    1,593|  9.2|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\noutliers <- bind_rows(head(latest %>% arrange(resid), 3),\n                      head(latest %>% arrange(desc(resid)), 3))\nggplot(latest, aes(gdpPercap, lifeExp)) +\n  geom_point(aes(size = pop, color = continent), alpha = 0.7) +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE,\n              color = \"grey30\", linetype = \"dashed\") +\n  geom_text(data = outliers, aes(label = country), size = 3, vjust = -1, check_overlap = TRUE) +\n  scale_x_log10(labels = scales::comma) +\n  scale_size(range = c(1, 12), guide = \"none\") +\n  labs(x = \"gdpPercap (log10)\", y = \"기대수명\", color = \"대륙\") + theme_minimal()\n```\n\n::: {.cell-output-display}\n![1인당 GDP vs 기대수명 — 점선=로그-선형 적합, 라벨=추세 최대 이탈국](eda_report_files/figure-html/fig-scatter-1.png){#fig-scatter width=1080}\n:::\n:::\n\n\n# 기대수명 순위 (2007년)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop10 <- latest %>% arrange(desc(lifeExp)) %>%\n  transmute(국가=country, 대륙=continent, 기대수명=round(lifeExp,2),\n            `1인당GDP`=round(gdpPercap)) %>% head(10)\nbot10 <- latest %>% arrange(lifeExp) %>%\n  transmute(국가=country, 대륙=continent, 기대수명=round(lifeExp,2),\n            `1인당GDP`=round(gdpPercap)) %>% head(10)\nkable(top10, format.args = list(big.mark=\",\"), caption = \"상위 10개국\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 상위 10개국\n\n|국가             |대륙     | 기대수명| 1인당GDP|\n|:----------------|:--------|--------:|--------:|\n|Japan            |Asia     |    82.60|   31,656|\n|Hong Kong, China |Asia     |    82.21|   39,725|\n|Iceland          |Europe   |    81.76|   36,181|\n|Switzerland      |Europe   |    81.70|   37,506|\n|Australia        |Oceania  |    81.24|   34,435|\n|Spain            |Europe   |    80.94|   28,821|\n|Sweden           |Europe   |    80.88|   33,860|\n|Israel           |Asia     |    80.75|   25,523|\n|France           |Europe   |    80.66|   30,470|\n|Canada           |Americas |    80.65|   36,319|\n\n\n:::\n\n```{.r .cell-code}\nkable(bot10, format.args = list(big.mark=\",\"), caption = \"하위 10개국\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 하위 10개국\n\n|국가                     |대륙   | 기대수명| 1인당GDP|\n|:------------------------|:------|--------:|--------:|\n|Swaziland                |Africa |    39.61|    4,513|\n|Mozambique               |Africa |    42.08|      824|\n|Zambia                   |Africa |    42.38|    1,271|\n|Sierra Leone             |Africa |    42.57|      863|\n|Lesotho                  |Africa |    42.59|    1,569|\n|Angola                   |Africa |    42.73|    4,797|\n|Zimbabwe                 |Africa |    43.49|      470|\n|Afghanistan              |Asia   |    43.83|      975|\n|Central African Republic |Africa |    44.74|      706|\n|Liberia                  |Africa |    45.68|      415|\n\n\n:::\n:::\n\n\n- 상위권은 유럽·동아시아 선진국, 하위권은 대부분 사하라 이남 아프리카.\n- 하위권 안에서도 **Swaziland·Angola는 소득이 4,500달러 이상**인데 수명이 최하위 — 소득만으로 설명되지 않는 보건 위기(HIV/AIDS·분쟁).\n\n# 변화 — 개선폭 **그리고** 후퇴/역전 (1952 → 2007)\n\n::: {.callout-note}\n기존 분석은 \"개선 상위\"만 보았다. 균형 잡힌 EDA는 같은 비중으로 **악화/후퇴**도 봐야 한다.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchange <- df %>%\n  group_by(country, continent) %>%\n  summarise(\n    le_start = lifeExp[which.min(year)],\n    le_end   = lifeExp[which.max(year)],\n    le_peak  = max(lifeExp),\n    gain     = lifeExp[which.max(year)] - lifeExp[which.min(year)],\n    drawdown = max(lifeExp) - lifeExp[which.max(year)],\n    .groups = \"drop\"\n  )\n\ngain10 <- change %>% arrange(desc(gain)) %>%\n  transmute(국가=country, 대륙=continent, `1952`=round(le_start,2),\n            `2007`=round(le_end,2), 증가폭=round(gain,2)) %>% head(10)\ndeclines <- change %>% filter(gain < 0) %>% arrange(gain) %>%\n  transmute(국가=country, 대륙=continent, `1952`=round(le_start,1),\n            `2007`=round(le_end,1), 증가폭=round(gain,1))\ndd10 <- change %>% arrange(desc(drawdown)) %>%\n  transmute(국가=country, 대륙=continent, 정점수명=round(le_peak,1),\n            `2007`=round(le_end,1), 하락폭=round(drawdown,1)) %>% head(10)\n\nkable(gain10, caption = \"기대수명 개선폭 상위 10개국\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 기대수명 개선폭 상위 10개국\n\n|국가               |대륙     |  1952|  2007| 증가폭|\n|:------------------|:--------|-----:|-----:|------:|\n|Oman               |Asia     | 37.58| 75.64|  38.06|\n|Vietnam            |Asia     | 40.41| 74.25|  33.84|\n|Indonesia          |Asia     | 37.47| 70.65|  33.18|\n|Saudi Arabia       |Asia     | 39.88| 72.78|  32.90|\n|Libya              |Africa   | 42.72| 73.95|  31.23|\n|Korea, Rep.        |Asia     | 47.45| 78.62|  31.17|\n|Nicaragua          |Americas | 42.31| 72.90|  30.59|\n|West Bank and Gaza |Asia     | 43.16| 73.42|  30.26|\n|Yemen, Rep.        |Asia     | 32.55| 62.70|  30.15|\n|Gambia             |Africa   | 30.00| 59.45|  29.45|\n\n\n:::\n\n```{.r .cell-code}\nkable(declines, caption = \"기간 내 순(純)후퇴 국가 (2007년 < 1952년)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 기간 내 순(純)후퇴 국가 (2007년 < 1952년)\n\n|국가      |대륙   | 1952| 2007| 증가폭|\n|:---------|:------|----:|----:|------:|\n|Zimbabwe  |Africa | 48.5| 43.5|   -5.0|\n|Swaziland |Africa | 41.4| 39.6|   -1.8|\n\n\n:::\n\n```{.r .cell-code}\nkable(dd10, caption = \"정점 대비 최대 후퇴(drawdown) 상위 10 — 중간의 붕괴 포착\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 정점 대비 최대 후퇴(drawdown) 상위 10 — 중간의 붕괴 포착\n\n|국가                     |대륙   | 정점수명| 2007| 하락폭|\n|:------------------------|:------|--------:|----:|------:|\n|Zimbabwe                 |Africa |     62.4| 43.5|   18.9|\n|Swaziland                |Africa |     58.5| 39.6|   18.9|\n|Lesotho                  |Africa |     59.7| 42.6|   17.1|\n|Botswana                 |Africa |     63.6| 50.7|   12.9|\n|South Africa             |Africa |     61.9| 49.3|   12.5|\n|Zambia                   |Africa |     51.8| 42.4|    9.4|\n|Namibia                  |Africa |     62.0| 52.9|    9.1|\n|Cote d'Ivoire            |Africa |     54.7| 48.3|    6.3|\n|Central African Republic |Africa |     50.5| 44.7|    5.7|\n|Iraq                     |Asia   |     65.0| 59.5|    5.5|\n\n\n:::\n:::\n\n\n- 순후퇴는 단 2개국이지만, **drawdown으로 보면 남부 아프리카 전역의 보건 붕괴(HIV/AIDS)** 가 뚜렷하다(보츠와나·남아공은 한때 60세 초과 → 50세 안팎으로 추락, 소득은 오히려 높음 → 잔차 분석과 동일 집단).\n- 시작·끝 두 점만 비교하면 이 위기를 **완전히 놓친다.** 이것이 개선폭만 보던 기존 분석의 가장 큰 사각지대였다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshock <- change %>% arrange(desc(drawdown)) %>% head(6) %>% pull(country)\ndf %>% filter(country %in% shock) %>%\n  ggplot(aes(year, lifeExp, color = country)) +\n  geom_line(linewidth = 1) + geom_point(size = 1.5) +\n  labs(x = \"연도\", y = \"기대수명\", color = \"국가\") + theme_minimal()\n```\n\n::: {.cell-output-display}\n![기대수명 후퇴가 컸던 국가들의 궤적 — HIV/AIDS·분쟁의 흔적](eda_report_files/figure-html/fig-reversals-1.png){#fig-reversals width=1080}\n:::\n:::\n\n\n# 결론\n\n1. **데이터 품질**: 균형 패널(142국 × 12년), 결측·중복·범위 위반 0건. 단, 원본 비(非)따옴표 CSV는 쉼표 국가명으로 열 밀림 위험 → `_clean.csv` 사용·라벨 검증 필수.\n2. **전반적 향상**: 1952–2007년 가중평균 기대수명 +20년, 소득 약 3.2배. 그러나 **수렴은 단조롭지 않고 U자형** — 1980년대 후반 최대 수렴 후 1990년대 재발산.\n3. **소득–수명 연관**: log10(GDP)와 강한 양의 상관(통합·단면 모두 ≈ 0.81)이나 **통합 상관은 시대·국가 효과의 혼합**이며, 연도별로 0.75–0.87을 오간다. 고소득 구간에서 수확 체감.\n4. **돈으로 설명 안 되는 사례**: 남부 아프리카(스와질란드·보츠와나·남아공)는 중상위 소득에도 HIV/AIDS로 수명 최하위(큰 음의 잔차); 베트남·니카라과 등은 저소득에도 우수한 보건 성과(큰 양의 잔차).\n5. **개선과 후퇴의 공존**: 오만·베트남·한국(+31년)이 빠르게 추격한 한편, **남부 아프리카는 정점 대비 12–19년 후퇴**했다. 개선만 보는 분석은 이 위기를 놓친다.\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"세션 정보 (재현성)\"}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> R version 4.6.0 (2026-04-24 ucrt)\n#> Platform: x86_64-w64-mingw32/x64\n#> Running under: Windows 11 x64 (build 26200)\n#> \n#> Matrix products: default\n#>   LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] LC_COLLATE=Korean_Korea.utf8  LC_CTYPE=Korean_Korea.utf8   \n#> [3] LC_MONETARY=Korean_Korea.utf8 LC_NUMERIC=C                 \n#> [5] LC_TIME=Korean_Korea.utf8    \n#> \n#> time zone: Asia/Seoul\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#> [1] dplyr_1.2.1   ggplot2_4.0.3 knitr_1.51   \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] vctrs_0.7.3        nlme_3.1-169       cli_3.6.6          rlang_1.2.0       \n#>  [5] xfun_0.59          otel_0.2.0         generics_0.1.4     S7_0.2.2          \n#>  [9] jsonlite_2.0.0     labeling_0.4.3     glue_1.8.1         htmltools_0.5.9   \n#> [13] scales_1.4.0       rmarkdown_2.31     grid_4.6.0         tibble_3.3.1      \n#> [17] evaluate_1.0.5     fastmap_1.2.0      yaml_2.3.12        lifecycle_1.0.5   \n#> [21] compiler_4.6.0     RColorBrewer_1.1-3 pkgconfig_2.0.3    mgcv_1.9-4        \n#> [25] lattice_0.22-9     farver_2.1.2       digest_0.6.39      R6_2.6.1          \n#> [29] tidyselect_1.2.1   splines_4.6.0      pillar_1.11.1      magrittr_2.0.5    \n#> [33] Matrix_1.7-5       withr_3.0.3        tools_4.6.0        gtable_0.3.6\n```\n\n\n:::\n:::",
    "supporting": [
      "eda_report_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}