{
  "hash": "da755b297eda64234b487c908badabf9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"gapminder EDA 대시보드\"\nauthor: \"yewonyu\"\ndate: \"2026-06-27\"\nlang: ko\nformat:\n  dashboard:\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n  echo: false\n---\n\n\n\n\n# 핵심 지표\n\n## Row {height=\"22%\"}\n\n\n::: {.cell content='valuebox' title='전세계 기대수명 2007 (1인 기준, 인구가중)'}\n::: {.cell-output .cell-output-stdout}\n\n```\n$icon\n[1] \"heart-pulse-fill\"\n\n$color\n[1] \"success\"\n\n$value\n[1] \"68.9세\"\n```\n\n\n:::\n:::\n\n::: {.cell content='valuebox' title='지난 55년간 기대수명 증가 (1952→2007)'}\n::: {.cell-output .cell-output-stdout}\n\n```\n$icon\n[1] \"graph-up-arrow\"\n\n$color\n[1] \"primary\"\n\n$value\n[1] \"+20.0년\"\n```\n\n\n:::\n:::\n\n::: {.cell content='valuebox' title='최장수–최단명 국가 격차 (2007)'}\n::: {.cell-output .cell-output-stdout}\n\n```\n$icon\n[1] \"rulers\"\n\n$color\n[1] \"danger\"\n\n$value\n[1] \"43년\"\n```\n\n\n:::\n:::\n\n\n## Row {height=\"78%\"}\n\n### Column {width=\"55%\"}\n\n\n::: {.cell title='전세계 기대수명 추세 (가중 vs 비가중)'}\n::: {.cell-output-display}\n![](eda_dashboard_files/figure-html/unnamed-chunk-4-1.png){width=768}\n:::\n:::\n\n\n### Column {width=\"45%\"}\n\n\n::: {.cell title='국가 간 격차(CV) — 수렴은 단조롭지 않다'}\n::: {.cell-output-display}\n\n\n| 연도|    SD|    CV|   IQR|\n|----:|-----:|-----:|-----:|\n| 1952| 12.23| 0.249| 20.71|\n| 1957| 12.23| 0.237| 21.79|\n| 1962| 12.10| 0.226| 21.77|\n| 1967| 11.72| 0.210| 21.39|\n| 1972| 11.38| 0.197| 20.75|\n| 1977| 11.23| 0.188| 19.91|\n| 1982| 10.77| 0.175| 17.98|\n| 1987| 10.56| 0.167| 16.94|\n| 1992| 11.23| 0.175| 16.46|\n| 1997| 11.56| 0.178| 18.54|\n| 2002| 12.28| 0.187| 19.94|\n| 2007| 12.07| 0.180| 19.25|\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## 노트\n국가 간 변동계수 **CV가 0.249(1952) → 최저 0.167(1987) → 0.180(2007)**.\n전반적으로 수렴했으나 1980년대 후반 이후 HIV/AIDS·체제전환으로 **재확대(발산)** — \"꾸준한 수렴\"은 사실이 아니다.\n:::\n\n# 가중 vs 비가중\n\n## Row\n\n\n::: {.cell title='기대수명: 인구가중 vs 비가중'}\n::: {.cell-output-display}\n![](eda_dashboard_files/figure-html/unnamed-chunk-6-1.png){width=768}\n:::\n:::\n\n::: {.cell title='1인당 GDP: 인구가중 vs 비가중'}\n::: {.cell-output-display}\n![](eda_dashboard_files/figure-html/unnamed-chunk-7-1.png){width=768}\n:::\n:::\n\n\n## Row\n\n### Column {width=\"60%\"}\n\n\n::: {.cell title='대륙별 기대수명 추세 (인구 가중)'}\n::: {.cell-output-display}\n![](eda_dashboard_files/figure-html/unnamed-chunk-8-1.png){width=768}\n:::\n:::\n\n\n### Column {width=\"40%\"}\n\n::: {.callout-tip}\n## 가중 vs 비가중, 무엇이 다른가\n- **인구가중 평균** = \"평균적 *인간*\"의 경험 (인구 많은 국가가 더 큰 비중)\n- **비가중 평균** = \"평균적 *국가*\" (룩셈부르크와 중국이 동등)\n- 1967년 이후 **인구가중 > 비가중** → 인구 대국(중국·인도)이 평균적 국가보다 빠르게 개선됨을 시사.\n- 단, 1962년에는 역전(가중 < 비가중) — 당시 중국 대약진 기근의 흔적.\n:::\n\n# 소득 ↔ 수명\n\n## Row {height=\"60%\"}\n\n### Column {width=\"60%\"}\n\n\n::: {.cell title='1인당 GDP vs 기대수명 (2007, 로그 스케일)'}\n::: {.cell-output-display}\n![](eda_dashboard_files/figure-html/unnamed-chunk-9-1.png){width=768}\n:::\n:::\n\n\n### Column {width=\"40%\"}\n\n\n::: {.cell title='연도별 단면 상관 (log10 GDP)'}\n::: {.cell-output-display}\n\n\n| 연도| 상관계수|\n|----:|--------:|\n| 1952|    0.748|\n| 1957|    0.759|\n| 1962|    0.771|\n| 1967|    0.773|\n| 1972|    0.789|\n| 1977|    0.814|\n| 1982|    0.846|\n| 1987|    0.874|\n| 1992|    0.856|\n| 1997|    0.864|\n| 2002|    0.825|\n| 2007|    0.809|\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## 노트\n통합 상관 0.81은 '국가 간 차이'와 '연도별 동반 상승'의 **혼합**. 연도별 단면 상관은 **0.75–0.87**을 오가며, 2007년 로그-선형 회귀 **R² = 0.654**.\n:::\n\n## Row {height=\"40%\"}\n\n\n::: {.cell title='소득 대비 기대수명이 낮은 국가 (음의 잔차) — HIV/AIDS 남부 아프리카'}\n::: {.cell-output-display}\n\n\n|              국가|   대륙| 기대수명| 1인당GDP|  잔차|\n|-----------------:|------:|--------:|--------:|-----:|\n|         Swaziland| Africa|     39.6|    4,513| -25.9|\n|            Angola| Africa|     42.7|    4,797| -23.3|\n|          Botswana| Africa|     50.7|   12,570| -22.2|\n|      South Africa| Africa|     49.3|    9,270| -21.4|\n| Equatorial Guinea| Africa|     51.6|   12,154| -21.1|\n\n\n:::\n:::\n\n::: {.cell title='소득 대비 기대수명이 높은 국가 (양의 잔차) — 저소득 고성과'}\n::: {.cell-output-display}\n\n\n|               국가|     대륙| 기대수명| 1인당GDP| 잔차|\n|------------------:|--------:|--------:|--------:|----:|\n|            Vietnam|     Asia|     74.2|    2,442| 13.1|\n|          Nicaragua| Americas|     72.9|    2,749| 10.9|\n| West Bank and Gaza|     Asia|     73.4|    3,025| 10.7|\n|            Comoros|   Africa|     65.2|      986| 10.5|\n|   Korea, Dem. Rep.|     Asia|     67.3|    1,593|  9.2|\n\n\n:::\n:::",
    "supporting": [
      "eda_dashboard_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}